version: '3.3'
services:
    run:
        container_name: alpine-sqs
        ports:
            - '9324:9324'
            - '9325:9325'
        volumes:
            - '/opt/alpine-sqs:/opt/custom'
        image: roribio16/alpine-sqs:latest